# Generated by Django 6.0.1 on 2026-04-27 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='hero_cta_link',
            field=models.CharField(default='/shop/', max_length=255),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_cta_text',
            field=models.CharField(default='Decouvrir les produits', max_length=60),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_subtitle',
            field=models.TextField(blank=True, default='Des references fiables pour vos chantiers residentiels et industriels.'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_title',
            field=models.CharField(default='Solutions de gaines electriques professionnelles', max_length=120),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='whatsapp_default_message',
            field=models.CharField(blank=True, default='Bonjour, je souhaite obtenir un devis pour des gaines electriques.', max_length=255),
        ),
    ]
