# Generated by Django 6.0.1 on 2026-04-27 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_sitesettings_hero_cta_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteimage',
            name='image_type',
            field=models.CharField(choices=[('banner', 'Bannière'), ('footer', 'Footer'), ('hero', 'Hero Section'), ('logo', 'Logo'), ('favicon', 'Favicon'), ('marketing', 'Marketing'), ('other', 'Autre')], max_length=20),
        ),
    ]
