# Generated by Django 6.0.1 on 2026-04-27 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_siteimage_image_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='primary_color',
            field=models.CharField(default='#facc15', max_length=7),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='primary_hover_color',
            field=models.CharField(default='#eab308', max_length=7),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='secondary_color',
            field=models.CharField(default='#0a0a0a', max_length=7),
        ),
    ]
