# Generated by Django 6.0.1 on 2026-04-27 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_sitesettings_primary_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='hero_badge_text',
            field=models.CharField(default='Materiel electrique professionnel', max_length=80),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_secondary_cta_link',
            field=models.CharField(default='/dashboard/', max_length=255),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_secondary_cta_text',
            field=models.CharField(default='Gerer le contenu', max_length=60),
        ),
        migrations.AlterField(
            model_name='siteimage',
            name='image_type',
            field=models.CharField(choices=[('top_carousel', 'Carousel pleine largeur'), ('banner', 'Bannière'), ('footer', 'Footer'), ('hero', 'Hero Section'), ('logo', 'Logo'), ('favicon', 'Favicon'), ('marketing', 'Marketing'), ('other', 'Autre')], max_length=20),
        ),
    ]
