# Generated by Django 6.0.1 on 2026-04-27 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_sitesettings_hero_badge_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='notification_email',
            field=models.EmailField(blank=True, help_text="Email de l'administrateur qui reçoit les notifications de commande", max_length=254),
        ),
    ]
