# Generated by Django 6.0.1 on 2026-04-27 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_add_notification_email_to_sitesettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingaddress',
            name='city',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
