# Generated by Django 6.0.1 on 2026-04-27 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_add_city_to_billing_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='view_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='PageView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=500)),
                ('date', models.DateField()),
                ('count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['-date', '-count'],
                'unique_together': {('path', 'date')},
            },
        ),
    ]
